export const PATHS = {
	home: "/",
	servicePages: {
		freshness: "/freshness",
		delivery: "/delivery",
		wholesale: "/wholesale",
		contacts: "/contacts",
		news: "/news",
		policy: "/policy",
		quality: "/quality",
	},
	mainMenu: {
		sweetDays: "/sweet-days",
		giftSets: "/gift-sets",
		teachesDay: "/teaches-day",
		allSets: "/all-sets",
		birthDay: "/birthday",
		classicMacarons: "/classic-macarons",
		weddingProposals: "/wedding-proposals",
		candyBars: "/candy-bars",
		corporateGifts: "/corporate-gifts",
		assembleSet: "/assemble-set",
		assembleDesign: "/assemble-design",
		companies: "/companies",
		createDesign: "/create-design",
		wholesaleSupplies: "/wholesale-supplies",
		eclairsWholesale: "/eclairs-wholesale",
		entireСatalog: "/entire-catalog",
		dessertCatalog: "/dessert-catalog",
		macarons: "/macarons",
		eclairs: "/eclairs",
		waffleCones: "/waffle-cones",
		cakePops: "/cake-pops",
		potatoDessert: "/potato-dessert",
		comboSets: "/combo-sets",
	},
} as const;

export type PathValue = (typeof PATHS)[keyof typeof PATHS];
