export const PATHS = {
	home: "/",
	servicePages: {
		freshness: "/freshness",
		delivery: "/delivery",
		wholesale: "/wholesale",
		contacts: "/contacts",
		policy: "/policy",
		quality: "/quality",
	},
	mainMenu: {
		womensDay: "/womens-day",
		fatherlandDay: "/fatherland-day",
		valentinesDay: "/valentines-day",
		childrensDay: "/childrens-day",
		dayKnowledge: "/day-knowledge",
		newYear: "/new-year",
		birthDay: "/birthday",
		addSales: "/add-sales",
		sweetDays: "/sweet-days",
		giftSets: "/gift-sets",
		teachesDay: "/teaches-day",
		allSets: "/all-sets",
		classicMacarons: "/classic-macarons",
		weddingProposals: "/wedding-proposals",
		candyBars: "/candy-bars",
		corporateGifts: "/corporate-gifts",
		assembleSet: "/assemble-set",
		assembleDesign: "/assemble-design",
		companies: "/companies",
		createDesign: "/create-design",
		wholesaleSupplies: "/wholesale-supplies",
		eclairsWholesale: "/eclairs-wholesale",
		entireСatalog: "/entire-catalog",
		macarons: "/catalog/macarons",
		eclairs: "/catalog/eclairs",
		waffleCones: "/catalog/wafer-rolls",
		potatoDessert: "/catalog/potato-dessert",
	},
} as const;

export type PathValue = (typeof PATHS)[keyof typeof PATHS];
