import { PATHS } from "@/shared/lib/paths";

export const holidaysData = {
	birthDay: {
		id: 1,
		allRussianHoliday: false,
		title: "День Рождения",
		path: PATHS.mainMenu.birthDay,
		cardColor: "#0e3250",
		imageUrl: "/images/holidays/images/happyDay.webp",
		pathIcon: "/images/holidays/icons/birthDay.svg",
	},
	mothersDay: {
		id: 2,
		date: "11-27",
		event: "",
		title: "День Матери",
		path: "",
		cardColor: "#52052f",
		imageUrl: "/images/holidays/images/mothersDay.webp",
		pathIcon: "/images/holidays/icons/mothersDay.svg",
	},
	newYear: {
		id: 3,
		date: "01-01",
		event: "31 Декабря",
		title: "Новый Год",
		path: PATHS.mainMenu.newYear,
		cardColor: "#255351",
		imageUrl: "/images/holidays/images/newYear.webp",
		pathIcon: "/images/holidays/icons/newYear.svg",
	},
	valentinesDay: {
		id: 4,
		date: "02-14",
		event: "14 Февраля",
		title: "День Святого Валентина",
		path: PATHS.mainMenu.valentinesDay,
		cardColor: "#b94b8f",
		imageUrl: "/images/holidays/images/valDay.webp",
		pathIcon: "/images/holidays/icons/valentinesDay.svg",
	},
	fatherlandDay: {
		id: 5,
		date: "02-23",
		event: "23 Февраля",
		title: "День Защитника Отечества",
		path: PATHS.mainMenu.fatherlandDay,
		cardColor: "#a83229",
		imageUrl: "/images/holidays/images/fatherlandDay.webp",
		pathIcon: "/images/holidays/icons/fatherlandDay.svg",
	},
	womensDay: {
		id: 6,
		date: "03-08",
		event: "8 Марта",
		title: "Международный Женский День",
		path: PATHS.mainMenu.womensDay,
		cardColor: "#abaa21",
		imageUrl: "/images/holidays/images/womensDay.webp",
		pathIcon: "/images/holidays/icons/womensDay.svg",
	},
	laborDay: {
		id: 7,
		date: "05-01",
		event: "1 Мая",
		title: "Праздник Весны и Труда",
		path: "",
		cardColor: "#650d5c",
		imageUrl: "/images/holidays/images/laborDay.webp",
		pathIcon: "/images/holidays/icons/laborDay.svg",
	},
	victoryDay: {
		id: 8,
		date: "05-09",
		event: "9 Мая",
		title: "День Победы",
		path: "",
		cardColor: "#2a0d65",
		imageUrl: "/images/holidays/images/victoryDay.webp",
		pathIcon: "/images/holidays/icons/victoryDay.svg",
	},
	childrensDay: {
		id: 9,
		date: "07-01",
		event: "1 Июня",
		title: "День защиты детей",
		path: PATHS.mainMenu.childrensDay,
		cardColor: "#41671d",
		imageUrl: "/images/holidays/images/kidsDay.webp",
		pathIcon: "/images/holidays/icons/childrensDay.svg",
	},
	dayKnowledge: {
		id: 10,
		date: "09-01",
		event: "1 Сентября",
		title: "День знаний",
		path: PATHS.mainMenu.dayKnowledge,
		cardColor: "#8c5118",
		imageUrl: "/images/holidays/images/dayKnowledge.webp",
		pathIcon: "/images/holidays/icons/dayKnowledge.svg",
	},
	nationalUnityDay: {
		id: 11,
		date: "11-04",
		event: "4 Ноября",
		title: "День Народного Единства",
		path: "",
		cardColor: "#0c5818",
		imageUrl: "/images/holidays/images/nationalUnityDay.webp",
		pathIcon: "/images/holidays/icons/nationalUnityDay.svg",
	},
} as const;
