export const holidaysData = {
	birthDay: {
		id: 1,
		isPrivateHoliday: false,
		title: "День рождения",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/birthDay.svg",
	},
	mothersDay: {
		id: 2,
		date: "11-27",
		title: "День матери",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/mothersDay.svg",
	},
	newYear: {
		id: 3,
		date: "01-01",
		title: "Новый год",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/newYear.svg",
	},
	valentinesDay: {
		id: 4,
		date: "02-14",
		title: "День святого валентина",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/valentinesDay.svg",
	},
	fatherlandDay: {
		id: 5,
		date: "02-23",
		title: "День защитника отечества",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/fatherlandDay.svg",
	},
	womensDay: {
		id: 6,
		date: "03-08",
		title: "Международный женский день",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/womensDay.svg",
	},
	laborDay: {
		id: 7,
		date: "05-01",
		title: "Праздник Весны и Труда",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/laborDay.svg",
	},
	victoryDay: {
		id: 8,
		date: "05-09",
		title: "День Победы",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/victoryDay.svg",
	},
	childrensDay: {
		id: 9,
		date: "07-01",
		title: "День защиты детей",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/childrensDay.svg",
	},
	dayKnowledge: {
		id: 10,
		date: "09-01",
		title: "День знаний",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/dayKnowledge.svg",
	},
	nationalUnityDay: {
		id: 11,
		date: "11-04",
		title: "День народного единства",
		path: "",
		cardColor: "",
		pathIcon: "/images/holidays/icons/nationalUnityDay.svg",
	},
} as const;
