import type { AddSalesItem, AssemblePromoItem } from "../types";

export const assembleSetData = [
	{
		id: 1,
		title: "Набор из 6 макарон",
		price: 490,
		type: "macaron",
		quantity: 6,
		image: "/images/assemble-set/promo-1.png",
	},
	{
		id: 2,
		title: "Набор из 12 макарон",
		price: 890,
		type: "macaron",
		quantity: 12,
		image: "/images/assemble-set/promo-2.png",
	},
	{
		id: 3,
		title: "Набор Сердце из 22 макарон",
		price: 2500,
		type: "macaron",
		quantity: 22,
		image: "/images/assemble-set/promo-3.png",
	},
	{
		id: 4,
		title: "Набор из 24 макарон",
		price: 1790,
		type: "macaron",
		quantity: 24,
		image: "/images/assemble-set/promo-4.png",
	},
	{
		id: 5,
		title: "Набор Круглый из 40 макарон",
		price: 4900,
		type: "macaron",
		quantity: 40,
		image: "/images/assemble-set/promo-5.png",
	},
	{
		id: 6,
		title: "Набор из 49 макарон",
		price: 3700,
		type: "macaron",
		quantity: 49,
		image: "/images/assemble-set/promo-6.png",
	},
	{
		id: 7,
		title: "Набор из 60 макарон",
		price: 5900,
		type: "macaron",
		quantity: 60,
		image: "/images/assemble-set/promo-7.png",
	},
] as const satisfies ReadonlyArray<AssemblePromoItem>;

export const addSalesData = [
	{
		id: 1,
		title: 'Открытка "Наслаждайся!"',	
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-1.png",
	},
	{
		id: 2,
		title: 'Открытка "Hug Me"',
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-2.jpg",
	},
	{
		id: 3,
		title: 'Открытка "Счастье ждет тебя"',
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-3.png",
	},
	{
		id: 4,
		title: 'Открытка "P.S. I Love You"',
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-4.jpg",
	},
	{
		id: 5,
		title: 'Открытка "Для тебя"',
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-5.jpg",
	},
	{
		id: 6,
		title: 'Открытка "Поздравляю"',
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-6.jpg",
	},
	{
		id: 7,
		title: 'Открытка "С праздником весны"',
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-7.jpg",
	},
	{
		id: 8,
		title: "Ленточка красная",
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-8.jpg",
	},
	{
		id: 9,
		title: "Ленточка зеленая",
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-9.jpg",
	},	
	{
		id: 10,
		title: "Ленточка синяя",
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-10.jpg",
	},
	{
		id: 11,
		title: "Ленточка белая",
		price: 50,
		quantity: 0,
		image: "/images/add-sales/sale-11.jpg",
	},
	{
		id: 12,
		title: "Ленточка бордовая",
		price: 50,								
		quantity: 0,
		image: "/images/add-sales/sale-12.jpg",
	},
] as const satisfies ReadonlyArray<AddSalesItem>;